name: DockerHub

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  ARCHS: "linux/amd64,linux/arm64,linux/arm64/v8,linux/arm/v7,linux/arm/v6"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        # with:
        #   platforms: ${{ env.ARCHS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # with:
        #   platforms: ${{ env.ARCHS }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Strongswan
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: taknok/strongswan:latest
